version: "3.7"

services:

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.11.3-management"
    ports:
    - "15672:15672"
    - "5672:5672"
    environment:
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf

  database:
    container_name: storage
    build: ./docker/database
    platform: linux/amd64
    ports:
    - "5406:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: gob
      POSTGRES_USER: gob
    volumes:
    - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  management_database:
    container_name: management_database
    image: amsterdam/postgres11
    platform: linux/amd64
    ports:
    - "5407:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: gob_management
      POSTGRES_USER: gob

volumes:
  gob-volume:
    external: true


networks:
  default:
    external: true
    name: gob-network
